version: '3'
services:
  postgres:
    image: postgres:14
    healthcheck:
      test: ["CMD", "pg_isready -d db -U airflow"]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=airflow
    volumes:
      - ./database/:/var/lib/postgresql/data

  scheduler:
    build: .
    command: poetry run airflow scheduler
    depends_on:
      - postgres
    restart: on-failure
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD@postgres:5432/db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - GOOGLE_APPLICATION_CREDENTIALS=/app/airflow/keys/bigmoneyservicekey.json
    volumes:
      - ./dags:/app/airflow/dags
      - ./data:/app/airflow/data
      - ./logs:/app/airflow/logs
      - /home/daniel/.gcp_keys/:/app/airflow/keys

  webserver:
      build: .
      command: poetry run scripts/entrypoint.sh
      depends_on:
        - postgres
        - scheduler
      restart: on-failure
      healthcheck:
        test: ["CMD", "-f", "/home/airflow/airflow-webserver.pid"]
        interval: 30s
        timeout: 30s
        retries: 3
      environment:
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD@postgres:5432/db
        - POSTGRES_DB=db
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_USER=airflow
        - GOOGLE_APPLICATION_CREDENTIALS=/app/airflow/keys/bigmoneyservicekey.json
      volumes:
        - ./dags:/app/airflow/dags
        - ./data:/app/airflow/data
        - ./logs:/app/airflow/logs
        - /home/daniel/.gcp_keys/:/app/airflow/keys
      ports:
        - 8080:8080

